version: "2.1"

services:

  gradle-thymeleaf-ee-app:
    #mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["gradle-thymeleaf-ee-app-data:/home/appuser"]
    ports:
    - "5005:5005"
    - "8080:8080"
    - "9990:9990"
    networks:
      public-net:
        aliases:
        - app

volumes:
  gradle-thymeleaf-ee-app-data: {}

networks:
  public-net:
    driver: bridge
